### ISSUE TITLE
Expose results from server

### ISSUE THREAD

**Issue by changhiskhan** [cloudera/navigator-sdk#19]
The normal response from the server should look like:

```
entities:
    count: 10
    errors: []
relations:
    count: 10
    errors: []
```
    
The model should understand this response and the client should return a reference to the user
